name: My first workflow

on: push

jobs:
    first_job:
        runs-on: unbuntu-latest
        steps:
        - name: welcome msg
          run: echo "first actions job"
          
        - name:
          run: ls
        
          