name: Needs keyword- multiple jobs

on:
    workflow_dispatch: 
#    schedule:
#      - cron: "*/1 * * * *"   
    # push


jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y
      
    - name: Execute cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
    
    - name: upload the dragon text file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text-file
        path: dragon.txt
      
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: download the dragon text file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file
    
    - name: Test file exists
      run: grep -i "dragon" dragon.txt
      
  deploy_job_3:
    needs: [build_job_1, test_job_2]
    runs-on: ubuntu-latest
    steps:

    - name: download the dragon text file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file        

    - name: Read File
      run: cat dragon.txt        
