name: Needs keyword- multiple jobs

on:
    push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y
      
    - name: Execute cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
    
    - name: Sleep for 30 seconds
      run: sleep 30
      
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: sleep for 10 seconds
      run: sleep 10
    
    - name: Test file exists
      run: grep -i "dragon" dragon.txt
      
  deploy_job_3:
    needs: [build_job_1, test_job_2]
    runs-on: ubuntu-latest
    steps:
    - name: Read File
      run: cat dragon.txt        
